### ISSUE TITLE
backports.zoneinfo问题

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#102]
pkg_resources.DistributionNotFound: The 'backports.zoneinfo; python_version < "3.9"' distribution was not found and is required by tzlocal
![image](https://user-images.githubusercontent.com/69783837/177005293-4ab53436-acb7-42d2-9e20-bb0a315fb178.png)

tzlocal 改成2.1就能用了,不知道有没有其他方法

**Comment by Ailitonia** [comment]
似乎是 APScheduler 上游问题，可以尝试将 python 版本更新到 3.9 以上试试

**Comment by lancer-wang** [comment]
但是我用的是3.10啊

**Comment by lancer-wang** [comment]
backports.zoneinfo在3.10版本被取消了,怪不得
