### ISSUE TITLE
数据导出失败

### ISSUE THREAD

**Issue by yokinanya** [Ailitonia/omega-miya#104]
报错：Multiple rows were found when exactly one was required
Log：[20220711-130533-INFO.log](https://github.com/Ailitonia/omega-miya/files/9082624/20220711-130533-INFO.log)

**Comment by Ailitonia** [comment]
你的好感度表 `UserFavorability` 中某个用户有两条或以上条好感度记录，可能是在网络波动的情况下用户尝试快速多次签到导致的，可以将日志等级调整为 `DEBUG` 尝试定位到该用户，手动在数据库中删除多余的重复行，在尝试重新导出即可。

**Comment by yokinanya** [comment]
好了，谢谢喵
