### ISSUE TITLE
omega_statistic插件生成的图片无法显示中文

### ISSUE THREAD

**Issue by ShianoQwQ** [Ailitonia/omega-miya#105]
![20220714112229](https://user-images.githubusercontent.com/26810611/178891309-edb4598d-088f-4b8b-9b88-06cdef860984.jpg)
如图。而OPM插件等生成的图可以正常显示。简单看了眼应该是文字的生成方式不一样？
statistic用的matplotlib做图表，字体是SimHei，而我系统是英文系统，默认没这个字体的锅？
运行环境：
Ubuntu 22.04 LTS
Python3.10.4

**Comment by Ailitonia** [comment]
应该是字体问题, 之后改成使用自带的字体资源好了

**Comment by Ailitonia** [comment]
Fixed in 11f98b0a8aec2ed5215c06c5305005a089ee9dd2
