### ISSUE TITLE
P站

### ISSUE THREAD

**Issue by DingJC17** [Ailitonia/omega-miya#108]
P站进不去啊，不能访问外网就会报错，然后一直卡住0.0

**Comment by Ailitonia** [comment]
请参考[培训说明](https://github.com/Ailitonia/omega-miya/wiki/%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)中关于“全局HTTP代理配置”的部分配置代理，bot 运行网络环境不能访问外网那肯定不能访问 pixiv 啊
