### ISSUE TITLE
Future: 多数据库支持

### ISSUE THREAD

**Issue by xh22805** [Ailitonia/omega-miya#111]

**Comment by Ailitonia** [comment]
抱歉，目前暂时还没有这个计划🤣

**Comment by Ailitonia** [comment]
重构时移除mysql方言以适配多种数据库：
- mysql
- postgresql
- sqlite

**Comment by Ailitonia** [comment]
多数据库支持未经充分测试，不能完全保证可用性，待后续正式发版

**Comment by Ailitonia** [comment]
根据 SQLAlchemy 对数据库的[支持情况](https://docs.sqlalchemy.org/en/20/dialects/index.html#included-dialects), 在可预见的时间内, 本项目的多数据库支持将仅包括:
- [PostgreSQL](https://docs.sqlalchemy.org/en/20/dialects/postgresql.html)
- [MySQL and MariaDB](https://docs.sqlalchemy.org/en/20/dialects/mysql.html)
- [SQLite](https://docs.sqlalchemy.org/en/20/dialects/sqlite.html)

**Comment by Ailitonia** [comment]
计划新增: alembic 管理数据库更新和迁移
