### ISSUE TITLE
机器人是启动了但是没反应 

### ISSUE THREAD

**Issue by 1103859909** [Ailitonia/omega-miya#112]
![Uploading QQ图片20220831023311.png…]()

**Comment by Ailitonia** [comment]
额 你的日志截图 好像上传失败了

**Comment by 1103859909** [comment]
是要发什么启动的指令吗  比如   /开机    之类的

**Comment by 1103859909** [comment]
![Uploading 无标题.png…]()

**Comment by 1103859909** [comment]
![Uploading 无标题.png…]()

**Comment by Ailitonia** [comment]
你这日志截图没一个上传成功的啊🤣

**Comment by 1103859909** [comment]
[新建 ZIP 压缩文件.zip](https://github.com/Ailitonia/omega-miya/files/9523719/ZIP.zip)

**Comment by 1103859909** [comment]
这样总该可以了把

**Comment by 1103859909** [comment]
谢谢
