### ISSUE TITLE
Future: 词云

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#115]
以及每周水群最多人
话说能不能获取一段时间内抢红包最多的人

**Comment by Ailitonia** [comment]
目前数据库已重构，词云功能考虑在下个版本就写😂

**Comment by Ailitonia** [comment]
Added in ee2e95bb6ef95f0555a882db831ee8c585fa974f e72159a459e5130cdae11cb130916b1f140bdc12 b2bec2c14083cd5673a01d54ca6857fdcca80e4b

待合并
