### ISSUE TITLE
不知道是不是bug

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#117]
![image](https://user-images.githubusercontent.com/69783837/204714250-8ec45d11-15bb-4ab3-9230-76dc13b99c26.png)
群友一次发了很多图片
![image](https://user-images.githubusercontent.com/69783837/204714318-98011b5c-406a-4c14-a391-361cb112b961.png)
机器人直接卡死，不知道什么原因导致的

**Comment by lancer-wang** [comment]
python 的cpu占用直接100%

**Comment by lancer-wang** [comment]
![image](https://user-images.githubusercontent.com/69783837/204720187-77119837-ac5c-4662-9fff-88f6de174e93.png)
根据我多次断点测试，似乎是卡在这里了

**Comment by Ailitonia** [comment]
日志也没有吗
我先尝试复现一下
