### ISSUE TITLE
##Help!

### ISSUE THREAD

**Issue by DearATRI** [Ailitonia/omega-miya#120]
![image](https://user-images.githubusercontent.com/95509909/206852250-2166a7be-4667-4a35-8b78-a24b516064f5.png)
Why can't I connect to the server of MySQL! Please help!  Thank you! Danke !

**Comment by Ailitonia** [comment]
请先检查 mysql 服务是否正常运行

> The error (2003) Can't connect to MySQL server on 'server' (10061) indicates that the network connection has been refused. You should check that there is a MySQL server running, that it has network connections enabled, and that the network port you specified is the one configured on the server.
https://dev.mysql.com/doc/refman/5.7/en/can-not-connect-to-server.html

**Comment by DearATRI** [comment]
![image](https://user-images.githubusercontent.com/95509909/206854462-6f166636-6c9d-4163-9668-b1014244643b.png)
I think the server of mysql is running well

**Comment by DearATRI** [comment]
![image](https://user-images.githubusercontent.com/95509909/206855564-0614aa39-d394-4d4b-b1ee-3ca31c6a5a1e.png)
Thank you! I've succeeded! Have a nice day in the Typemoon World!
