### ISSUE TITLE
没看很懂ONEBOT_ACCESS_TOKEN和ONEBOT_SECRET具体对应go-cqhttp里的什么

### ISSUE THREAD

**Issue by ultragalaxy2018** [Ailitonia/omega-miya#121]
纯小白，最近才开始研究机器人怎么配置，只有一点py入门基础，搭建虚拟环境什么的因为别的地方学过所以摸索两下就懂了，但是这个参数实在看不懂。在congfig.yml里找了倒是有看到一个access-token，但是只有一项，没有sceret，而且access_token对应的不就是访问密钥么？？

**Comment by Ailitonia** [comment]
在 Onebot v11 中，通信有两种鉴权方式
HTTP POST 使用[签名](https://github.com/botuniverse/onebot-11/blob/master/communication/http-post.md#%E7%AD%BE%E5%90%8D)，`secret` 即为签名密钥
HTTP、正向 WebSocket、反向 WebSocket 中使用 `access token` 进行[验证](https://github.com/botuniverse/onebot-11/blob/master/communication/authorization.md)
配置说明见 onebot adapter [文档](https://onebot.adapters.nonebot.dev/docs/guide/configuration)

**Comment by Ailitonia** [comment]
omega-miya 默认使用反向 WebSocket 作为通讯方式，其实可以忽略 `ONEBOT_SECRET` 配置
