### ISSUE TITLE
NHentai模块报503

### ISSUE THREAD

**Issue by MaboroneSeika** [Ailitonia/omega-miya#122]
尝试了搜索和下载， 都无法成功，后台会报503，不知道大佬还维护这个插件吗？

01-11 12:46:49 [DEBUG] nonebot | Running matcher <Matcher from omega_miya.plugins.nhentai, type=message, priority=0, temp=True>

01-11 12:46:49 [DEBUG] nonebot | Running handler <Dependent call=<function handle_operating at 0x000002001FD0B130>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='event', type=MessageEvent, required=True), ModelField(name='matcher', type=Matcher, required=True), ModelField(name='operating', type=str, required=True), ModelField(name='operation_arg', type=str, required=True)], parameterless=[DependParam(), DependParam()]>

01-11 12:46:49 [DEBUG] nonebot | OneBot V11 | Calling API send_msg

01-11 12:46:50 [ERROR] omega_miya | SemaphoreGather | Task(s) called by "handle_search" in "E:\QQrobot\omega-miya-0.9\omega_miya\plugins\nhentai\__init__.py" raised NhentaiNetworkError exception in task(0), NhentaiNetworkError('NhentaiNetworkError, status code 503')

01-11 12:46:50 [ERROR] omega_miya | SemaphoreGather | Task(s) called by "handle_search" in "E:\QQrobot\omega-miya-0.9\omega_miya\plugins\nhentai\__init__.py" raised NhentaiNetworkError exception in task(1), NhentaiNetworkError('NhentaiNetworkError, status code 503')

01-11 12:46:50 [ERROR] omega_miya | SemaphoreGather | Task(s) called by "handle_search" in "E:\QQrobot\omega-miya-0.9\omega_miya\plugins\nhentai\__init__.py" raised NhentaiNetworkError exception in task(2), NhentaiNetworkError('NhentaiNetworkError, status code 503')

01-11 12:46:50 [ERROR] omega_miya | SemaphoreGather | Task(s) called by "handle_search" in "E:\QQrobot\omega-miya-0.9\omega_miya\plugins\nhentai\__init__.py" raised NhentaiNetworkError exception in task(3), NhentaiNetworkError('NhentaiNetworkError, status code 503')

01-11 12:46:50 [ERROR] omega_miya | SemaphoreGather | Task(s) called by "handle_search" in "E:\QQrobot\omega-miya-0.9\omega_miya\plugins\nhentai\__init__.py" raised NhentaiNetworkError exception in task(4), NhentaiNetworkError('NhentaiNetworkError, status code 503')

01-11 12:46:50 [DEBUG] nonebot | OneBot V11 | Calling API send_msg

01-11 12:46:50 [INFO] nonebot | Matcher <Matcher from omega_miya.plugins.nhentai, type=message, priority=0, temp=True> running complete

**Comment by Ailitonia** [comment]
NHentai 目前启用了 cloudflare 人机验证，目前考虑终止该插件维护
后续版面计划改为接入 Exhentai
