### ISSUE TITLE
签到报错

### ISSUE THREAD

**Issue by ANGJustinl** [Ailitonia/omega-miya#123]
我把sign的插件试着单独拆出来了，但是目前来看连不上数据库，数据集使用您在readme中提到的
且我已按照wiki进行配置

---

01-26 18:01:46 [DEBUG] sign | src.plugins.sign.database.schemas.bot_self._query_custom_one > operating failed, QueryOrmFailed, error: NoResultFound('No row was found when one was required')
01-26 18:01:46 [DEBUG] sign | src.plugins.sign.database.schemas.bot_self._query_unique_one > operating failed, NoResultFound
01-26 18:01:46 [ERROR] sign | Decorator RunAsyncCatchingException | src.plugins.sign.database.internal.entity.get_friendship_model raise AssertionError > Query bot self model failed
01-26 18:01:46 [DEBUG] sign | src.plugins.sign.database.schemas.bot_self._query_custom_one > operating failed, QueryOrmFailed, error: NoResultFound('No row was found when one was required')
01-26 18:01:46 [DEBUG] sign | src.plugins.sign.database.schemas.bot_self._query_unique_one > operating failed, NoResultFound

---

![image](https://user-images.githubusercontent.com/96008766/214808827-5a6b1fcb-d6d2-4d72-85ae-903d9f2ddaa9.png)

**Comment by Ailitonia** [comment]
大概率是 bot 没有初始化，数据库中没有当前 bot 的信息
需要使用这个函数对当前bot进行初始化
https://github.com/Ailitonia/omega-miya/blob/c8de61c78f083b51c88ee5c9f45a0b2b4bb05d5b/omega_miya/database/internal/bot.py#L73
