### ISSUE TITLE
nh下载漫画,发送到群里的全都是第一张

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#13]
但是下载到本地的却是正确的
![image](https://user-images.githubusercontent.com/69783837/115361138-dd2fff80-a1f2-11eb-8b38-7bf0cc7755d5.png)

**Comment by lancer-wang** [comment]
看错了,里面都是最后一张

**Comment by Ailitonia** [comment]
已在 52a0de0fb24e0a0763f21a82a95a5b0739ac736d 修复

**Comment by lancer-wang** [comment]
实测可用,感谢
