### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by JIAFALSEDREAM** [Ailitonia/omega-miya#132]
小白一个
![30a4f85818249959c79a34d4702d7a4](https://github.com/Ailitonia/omega-miya/assets/121747365/1378cfba-047b-4f57-9fc6-08ab50b8bb99)

不知道是哪的问题 bing也没搜到解决办法
配置文件只改了超管和数据库(这不需要贴上来罢？)

**Comment by Ailitonia** [comment]
贴一下 `python -V` 以及 `pip list` 的输出, 你是不是版本混装了

**Comment by JIAFALSEDREAM** [comment]
![887af51349a0cad7c401e69829f8131](https://github.com/Ailitonia/omega-miya/assets/121747365/c8621c4e-c0ae-453b-b7a4-8909c97e11bc)
![fba57fade8de744fd1d8798575468f0](https://github.com/Ailitonia/omega-miya/assets/121747365/fe61ed94-263a-46a9-ba3d-397180fb692f)
![0a0e72d1fed7125bdd0ed7c50bbf221](https://github.com/Ailitonia/omega-miya/assets/121747365/9c14e691-509f-4567-8176-9f08ddd82024)

**Comment by Ailitonia** [comment]
Python 环境坏了, 重新安装后再试试, 需要 3.10+ 以上版本的 Python 环境 -> [3.10.11](https://www.python.org/downloads/release/python-31011/)

**Comment by JIAFALSEDREAM** [comment]
谢佬我去试试
