### ISSUE TITLE
求助：启动机器人时报错：加载插件失败

### ISSUE THREAD

**Issue by longyajr** [Ailitonia/omega-miya#142]
如题，跟着wiki走到时候 python bot.py 后似乎显示所有的插件都没能成功加载。应该怎么解决呢？
![image](https://github.com/Ailitonia/omega-miya/assets/66113106/17695d6a-4d06-45ec-8c97-e670c0c16bc2)
报错日志如下：
[20240610-181050-ERROR.log](https://github.com/user-attachments/files/15764174/20240610-181050-ERROR.log)

**Comment by Ailitonia** [comment]
完蛋 模块的导入部分忘对启用的适配器做判断了
先暂时安装所有的依赖来解决吧
```poetry install --all-extras```

**Comment by Ailitonia** [comment]
平台适配部分不太好改, 直接安装所有适配器得了😂

**Comment by Ailitonia** [comment]
反向ws是客户端来连接 nonebot 的反向 ws 地址, 另外就是确认一下客户端和 nonebot 的 token 都配置了而且都是一致的

**Comment by longyajr** [comment]
尝试配置了一个token，但好像还是有问题，报错跟之前一样
感觉是我缺少了什么两边都没提到的步骤……
napcat的配置文件：
![image](https://github.com/Ailitonia/omega-miya/assets/66113106/9481a95e-50e0-4f5c-8a83-a30b41398541)
nonebot的配置文件：
![image](https://github.com/Ailitonia/omega-miya/assets/66113106/d33e0287-8235-4d36-ab72-ba1924b0e1a3)

**Comment by Ailitonia** [comment]
![image](https://github.com/Ailitonia/omega-miya/assets/41713304/34b03c3e-c3bf-4b10-8f64-337d7fc2f71a)
用反向ws的话这里应该写 ws://127.0.0.1:14120/onebot/v11/ws

**Comment by longyajr** [comment]
现在两边的地址都改为127:0:0:1了，报错不变

**Comment by Ailitonia** [comment]
nonebot的日志有吗

**Comment by longyajr** [comment]
我感觉nonebot根本就没有接收到来自napcat的访问……
[20240611-233235-INFO.log](https://github.com/user-attachments/files/15791636/20240611-233235-INFO.log)

**Comment by Ailitonia** [comment]
![image](https://github.com/Ailitonia/omega-miya/assets/41713304/8b8f8d1c-4319-4e21-8a3c-ab185a947550)
把日志级别改成 `DEBUG` 再打一份日志看看呢

**Comment by longyajr** [comment]
奇怪，控制台显示DEBUG级别了，但是日志文件还是INFO级别的？
[20240612-001711-INFO.log](https://github.com/user-attachments/files/15792146/20240612-001711-INFO.log)
![image](https://github.com/Ailitonia/omega-miya/assets/66113106/443c8ba5-53c5-45f7-886e-ed333f31a652)

**Comment by Ailitonia** [comment]
看看日志前面 有没有
`[DEBUG] nonebot | Succeeded to load adapter "OneBot V11"`
`[DEBUG] nonebot | Loaded adapters: OneBot V11`
这几行
如果有的话那可能是客户端那边的问题 建议去那边社区问问怎么配置

**Comment by Ailitonia** [comment]
等下 你napcat是用的docker部署 然后nonebot是在docker外面运行的？

**Comment by longyajr** [comment]
嗯是的，napcat在docker上，所以其实两者的本地网络并不是同一个，所以127.0.0.1是访问不到彼此的。
所以在napcat上配置成我宿主机的内网地址，然后宿主机再配置一个端口映射（这步可能多余），就能成功访问nonebot了
说到底，还是因为我之前并没有这些概念，所以根本识别不到问题。
安里喂，多谢您的协助😇
