### ISSUE TITLE
关于发送gif

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#146]
经过我的多次尝试

发现在tg上，用OmegaMessageSegment.image 这个是不可行的

但是用OmegaMessageSegment.file(file=Path(paths)) 就可以

![image](https://github.com/Ailitonia/omega-miya/assets/69783837/d5d74ba1-065d-4018-82e5-979446d8a2be)

![image](https://github.com/Ailitonia/omega-miya/assets/69783837/5c1071d2-14e7-4f8a-9471-0b80ac610d30)

**Comment by lancer-wang** [comment]
用OmegaMessageSegment.image 发送出去的，直接是静态图

![image](https://github.com/Ailitonia/omega-miya/assets/69783837/28e45c45-5ed7-4c69-be6b-6ec8db7ec346)

**Comment by Ailitonia** [comment]
确实 这里是不同平台处理发送图片不同方法导致的
这里建议使用 `OmegaMessageSegment.image_file` 来发送 tg 平台的原图或 gif
之后有空大概会清理下以前插件里面涉及图片发送的部分

**Comment by lancer-wang** [comment]
> 确实 这里是不同平台处理发送图片不同方法导致的 这里建议使用 `OmegaMessageSegment.image_file` 来发送 tg 平台的原图或 gif 之后有空大概会清理下以前插件里面涉及图片发送的部分

image_file 好像有图片的大小限制，直接用文件格式似乎更好
