### ISSUE TITLE
Future: 自定义签到头图

### ISSUE THREAD

**Issue by longyajr** [Ailitonia/omega-miya#148]
如题，能否将签到的头图设定为从自己上传的若干张图片中选择一个呢？如果可以，应该怎么做呢？
另外，我希望可以在签到的时候生成一个今日运势（如大吉、大凶）的功能，如果要添加这部分功能，大概需要在代码的哪个位置添加呢？
望作者指导。

**Comment by Ailitonia** [comment]
第一个有点麻烦，现在的签到插件是直接用的 pixiv 的模块来随机头图的，不过现在正在整合其他图站，等到时候在加一个本地图片的适配，才能再来调整签到插件
第二个今日运势有现成的函数 `get_fortune`，直接拿来用就行
https://github.com/Ailitonia/omega-miya/blob/78a76f7ac31ba0bcab69cee39bb9b16f62aad6d0/src/plugins/omega_sign_in/helpers.py#L108

**Comment by Ailitonia** [comment]
Completed in #151
