### ISSUE TITLE
能不能在配置文件里设置各个插件的开关

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#15]
因为我没有配置b站的东西,所以一直看到提示获取b站直播信息失败,由此想到的,可以加个插件开关的功能

**Comment by Ailitonia** [comment]
之后会考虑设置配置或者使用load_from_json/load_from_toml加载插件
目前可以直接删除不需要的插件
omega_miya/plugins/ 内的插件可以直接删除而不影响整体

**Comment by Ailitonia** [comment]
这里好像也算是bug，没有订阅的时候应该不检测直播间才对，我先改下这个😂

**Comment by lancer-wang** [comment]
居然是bug...我以为是默认检测

**Comment by Ailitonia** [comment]
fix in 922c74f20d78dd658db61198e5fc4e4aa508025c
