### ISSUE TITLE
【bug？】启动之后反代连不上

### ISSUE THREAD

**Issue by mengluo04** [Ailitonia/omega-miya#154]
LLonebot和[Lagrange都连不上，提示403，配置是默认的没改

**Comment by Ailitonia** [comment]
1. 检查 `ONEBOT_ACCESS_TOKEN` 是否配置, 未配置或留空都是不行的
2. 如果使用 docker 等容器, 检查路径映射是否配置

**Comment by mengluo04** [comment]
> 1. 检查 `ONEBOT_ACCESS_TOKEN` 是否配置, 未配置或留空都是不行的
> 2. 如果使用 docker 等容器, 检查路径映射是否配置

直接复制的.env.example改名.env.dev，.env里面设置了环境为dev
`ENVIRONMENT=dev`
```env
# NoneBot2 配置
DRIVER=~fastapi+~aiohttp
HOST=127.0.0.1
PORT=3322
LOG_LEVEL=INFO
API_TIMEOUT=60.0
SUPERUSERS=["1263041461"]
NICKNAME=["omega"]
COMMAND_START=["/", "!", "！", "#"]
COMMAND_SEP=["."]
SESSION_EXPIRE_TIMEOUT=0d,00:01:00

# 数据库配置
DATABASE=sqlite
DB_DRIVER=aiosqlite
# DB_HOST=
# DB_PORT=
# DB_USER=
# DB_PASSWORD=
DB_NAME=omega_miya
DB_PREFIX=omega_miya_

# 全局HTTP代理配置
ENABLE_PROXY=false
PROXY_TYPE=http
PROXY_ADDRESS=127.0.0.1
PROXY_PORT=1081

# OneBot 协议配置
# vONEBOT_ACCESS_TOKEN=
# ONEBOT_SECRET=

# QQ 协议配置
# QQ_IS_SANDBOX=true
# QQ_BOTS=[]

# Telegram 协议配置
# TELEGRAM_BOTS=[]
# TELEGRAM_PROXY=

# Console 配置
# ENABLE_CONSOLE=false

# 全局AES加密密钥
AES_KEY=qwe!@#890

# 腾讯云API配置
TENCENT_CLOUD_SECRET_ID=
TENCENT_CLOUD_SECRET_KEY=

# 识图插件 Saucenao API KEY
SAUCENAO_API_KEY=

# Pixiv Cookie配置, 不填的话r18作品获取不到全部图片链接, 另外请确认P站用户设置-浏览限制中启用r18显示
PIXIV_PHPSESSID=

```

**Comment by Ailitonia** [comment]
https://github.com/Ailitonia/omega-miya/blob/9b66fa8d203609e5971c2740d178c0105153bc01/.env.sample#L29-L31

第 30 行取消注释, 配置为与 LLonebot 或 Lagrange 一致的 token, 另还有问题请再附上日志

**Comment by mengluo04** [comment]
> https://github.com/Ailitonia/omega-miya/blob/9b66fa8d203609e5971c2740d178c0105153bc01/.env.sample#L29-L31
> 
> 第 30 行取消注释, 配置为与 LLonebot 或 Lagrange 一致的 token, 另还有问题请再附上日志

设置之后可以，我用其他nb2项目的不用设置页没问题
Lagrange 配置这样的
```json
    "Implementations": [
        {
            "Type": "ReverseWebSocket",
            "Host": "127.0.0.1",
            "Port": 3322,
            "Suffix": "/onebot/v11/ws",
            "ReconnectInterval": 5000,
            "HeartBeatInterval": 5000,
            "AccessToken": ""
        }
    ]
```

**Comment by Ailitonia** [comment]
Lagrange 请配置 `AccessToken`

要求配置 `ONEBOT_ACCESS_TOKEN` 有包括但不限于以下原因
- 安全性考虑
- 多平台 bot 接入时判断启用适配器

**Comment by mengluo04** [comment]
> Lagrange 请配置 `AccessToken`
> 
> 要求配置 `ONEBOT_ACCESS_TOKEN` 有包括但不限于以下原因
> 
> * 安全性考虑
> * 多平台 bot 接入时判断启用适配器

ok，127.0.0.1应该不存在安全问题，多平台倒是没有过，都是用onebot
