### ISSUE TITLE
【功能建议】在订阅消息推送是增加关键词过滤

### ISSUE THREAD

**Issue by mengluo04** [Ailitonia/omega-miya#156]
满足关键词的消息不进行推送

**Comment by Ailitonia** [comment]
能举例说明下有哪些具体的场景吗？比如哪个平台的订阅，屏蔽的关键词是什么类型

**Comment by mengluo04** [comment]
> 能举例说明下有哪些具体的场景吗？比如哪个平台的订阅，屏蔽的关键词是什么类型

我主要是用b站的动态订阅，转发和抽奖相关的动态不需要推送。
看了下代码，感觉应该在这里判断，但是不太会处理
![image](https://github.com/user-attachments/assets/e29e6856-11a5-45e5-8f04-4928b451255b)

**Comment by Ailitonia** [comment]
我个人觉得，订阅或者说关注社交平台上的其他用户并接收其消息推送，代表你在订阅或者关注该用户时就可以预见其发布信息内容并对其有预期。

就如同微博、bilibili 都不会有通过关键词屏蔽内容的功能，这也不是因为不能做或者不好做，平台是因为要恰饭，我是觉得没必要。

所以如果你觉得转发抽奖相关动态太多的话，**最简单的解决方法是直接取关**。

当然，如果你实在需要对这个功能的话，可以在对这里对发送消息的 `_msg_sender` 方法进行修改：

https://github.com/Ailitonia/omega-miya/blob/64f265eb50c9eade514d689221f7ad2c811ba8e5/src/plugins/bilibili_dynamic_monitor/helpers.py#L158-L172

在发送前进行关键词检测：

```python3
async def _msg_sender(entity: "Entity", message: str | OmegaMessage) -> None:
    """向 entity 发送动态消息"""
    if isinstance(message, OmegaMessage):
        message_text = message.extract_plain_text()
    else:
        message_text = str(message)

    # 正则匹配关键词
    if re.search(r'(抽奖|转发)', message_text):
        return

    # 或者其他判断方法
    if check_blacklist(message_text):
        return

    try:
        async with begin_db_session() as session:
            internal_entity = await OmegaEntity.init_from_entity_index_id(session=session, index_id=entity.id)
            ...
```

即可实现发送前进行关键词过滤的功能

**Comment by mengluo04** [comment]
> 我个人觉得，订阅或者说关注社交平台上的其他用户并接收其消息推送，代表你在订阅或者关注该用户时就可以预见其发布信息内容并对其有预期。
> 
> 就如同微博、bilibili 都不会有通过关键词屏蔽内容的功能，这也不是因为不能做或者不好做，平台是因为要恰饭，我是觉得没必要。
> 
> 所以如果你觉得转发抽奖相关动态太多的话，**最简单的解决方法是直接取关**。
> 
> 当然，如果你实在需要对这个功能的话，可以在对这里对发送消息的 `_msg_sender` 方法进行修改：
> 
> https://github.com/Ailitonia/omega-miya/blob/64f265eb50c9eade514d689221f7ad2c811ba8e5/src/plugins/bilibili_dynamic_monitor/helpers.py#L158-L172
> 
> 在发送前进行关键词检测：
> 
> ```python
> async def _msg_sender(entity: "Entity", message: str | OmegaMessage) -> None:
>     """向 entity 发送动态消息"""
>     if isinstance(message, OmegaMessage):
>         message_text = message.extract_plain_text()
>     else:
>         message_text = str(message)
> 
>     # 正则匹配关键词
>     if re.search(r'(抽奖|转发)', message_text):
>         return
> 
>     # 或者其他判断方法
>     if check_blacklist(message_text):
>         return
> 
>     try:
>         async with begin_db_session() as session:
>             internal_entity = await OmegaEntity.init_from_entity_index_id(session=session, index_id=entity.id)
>             ...
> ```
> 
> 即可实现发送前进行关键词过滤的功能

非常感谢，我修改本地代码来实现
