### ISSUE TITLE
Future: 非文本消息持久化储存工具

### ISSUE THREAD

**Issue by yokinanya** [Ailitonia/omega-miya#159]
目前qqnt的图片url中有一个rkey，并且rkey是有时效性的。直接把收到的消息保存后，在一段时间后就会因为图片链接失效导致无法正常发出欢迎消息。

暂时有几个想法：
1. 把图传到图床
2. 存到本地
3. 转换成base64存储到数据库

**Comment by Ailitonia** [comment]
存本地缓存吧，图床还要引入外部依赖，base64存数据库有点傻（
