### ISSUE TITLE
问个问题,非bug

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#16]
我自己写了一些ghs的插件,发的内容都比较那啥
我想起之前在tg的时候,那边很多机器人都是发完一段时间后自动撤回
这个框架能做自动撤回吗

**Comment by Ailitonia** [comment]
nonebot2框架不都是想怎么写就怎么写吗😂
用个字典存bot发送的消息id和过期时间，用计划任务定时撤回就好了

**Comment by lancer-wang** [comment]
我去了解一下

**Comment by lancer-wang** [comment]
麻烦一下,再问个问题
我想做个合并转发
[CQ:node,user_id=2023294774,nickname=消息发送者某,content=&#91;CQ:image&#44;file=file:///F:/svapca/dou_pic/66824217_p0.jpg&#93;
插画名称：Vajra -Granblue Fantasy-
插画作者：Oz
插画ID:66824217
tags：グランブルーファンタジー 碧蓝幻想 女の子 女孩子 ヴァジラ 瓦姬拉 けもみみ 兽耳 魅惑のふともも 魅惑的大腿 はいてない 真空 タイツ 裤袜 黒スト 黑丝袜 
剩余调用次数：280]
这个是我用MessageSegment.node_custom生成的数据,但是发送的时候报错
![image](https://user-images.githubusercontent.com/69783837/115984359-53f54000-a5d9-11eb-8cc9-bc33cd4592d5.png)
你知道为啥吗

**Comment by lancer-wang** [comment]
补充一下调用
![image](https://user-images.githubusercontent.com/69783837/115984416-91f26400-a5d9-11eb-9224-78d0a1687cf5.png)

**Comment by Ailitonia** [comment]
qq风控，与nb无关，看gocq日志

**Comment by Ailitonia** [comment]
合并转发那你不能直接使用send发送，应该call_api('send_group_forward_msg', ...)
参考[gocq文档 发送合并转发-群](https://docs.go-cqhttp.org/api/#%E5%8F%91%E9%80%81%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91-%E7%BE%A4)

**Comment by lancer-wang** [comment]
> 合并转发那你不能直接使用send发送，应该call_api('send_group_forward_msg', ...)
> 参考[gocq文档 发送合并转发-群](https://docs.go-cqhttp.org/api/#%E5%8F%91%E9%80%81%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91-%E7%BE%A4)

这个我找到了,就是被风控了,我资讯其他人,发现合并转发比一般发更容易被风控....

**Comment by lancer-wang** [comment]
> nonebot2框架不都是想怎么写就怎么写吗😂
> 用个字典存bot发送的消息id和过期时间，用计划任务定时撤回就好了

撤回搞定了,问题是计划任务怎么添加?我看了下有个scheduler = require("nonebot_plugin_apscheduler").scheduler
但是这个是定时任务,难道要设置成一秒一触发吗

**Comment by lancer-wang** [comment]
> > nonebot2框架不都是想怎么写就怎么写吗😂
> > 用个字典存bot发送的消息id和过期时间，用计划任务定时撤回就好了
> 
> 撤回搞定了,问题是计划任务怎么添加?我看了下有个scheduler = require("nonebot_plugin_apscheduler").scheduler
> 但是这个是定时任务,难道要设置成一秒一触发吗
我试了用定时任务,结果发现无法定位bot
![image](https://user-images.githubusercontent.com/69783837/118609792-ae0aaf00-b7ed-11eb-9d80-4a6958dc7be7.png)

**Comment by Ailitonia** [comment]
> > > nonebot2框架不都是想怎么写就怎么写吗😂
> > > 用个字典存bot发送的消息id和过期时间，用计划任务定时撤回就好了
> > 
> > 
> > 撤回搞定了,问题是计划任务怎么添加?我看了下有个scheduler = require("nonebot_plugin_apscheduler").scheduler
> > 但是这个是定时任务,难道要设置成一秒一触发吗
> > 我试了用定时任务,结果发现无法定位bot
> > ![image](https://user-images.githubusercontent.com/69783837/118609792-ae0aaf00-b7ed-11eb-9d80-4a6958dc7be7.png)

看[文档](https://v2.nonebot.dev/api/nonebot.html#get-bots)
用 nonebot.get_bots() 获取 Bot 对象
