### ISSUE TITLE
P站图片链接感觉可以替换成pixiv.cat的

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#19]
.replace("i.pximg.net", "i.pixiv.cat")
试了下,感觉下载速度快了不少,也不用加header了

**Comment by Ailitonia** [comment]
这其实算是个设计问题……
pixiv模块使用的就是p站本身api，要么外网部署，要么使用代理，否则是获取不到作品信息的
然而上述两种情况，都会比使用pixiv.cat代理的速度要更快😂

**Comment by lancer-wang** [comment]
i got it
