### ISSUE TITLE
闪照功能

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#23]
其实我自己做了，不过做的比较糙,在nonebot2_miya/omega_miya/utils/Omega_plugin_utils/rules.py中添加
from nonebot.adapters.cqhttp import MessageEvent
def has_flash_permission() -> Rule:
    async def _has_flash_permission(bot: Bot, event: MessageEvent, state: T_State) -> bool:
        msg = str(event.get_message())
        # 检查当前消息类型
        if 'type=flash,' in msg:
            return True
        else:
            return False
    return Rule(_has_flash_permission)
就能检测闪照了
顺便吐槽一句,github的代码块功能真烂

**Comment by Ailitonia** [comment]
这样检测闪照的确没有问题，不过我觉得写成rule的话可能用起来使用范围比较小，倒不如摸一个通用的反闪照插件:D

**Comment by Ailitonia** [comment]
既然反闪照都做了，那不如防撤回也一起做了吧:D

- TODO
    - 反闪照插件
    - 防撤回插件

**Comment by lancer-wang** [comment]
防撤回我原本想加上,后来想了想还是注释掉了,没敢加上

**Comment by Ailitonia** [comment]
Added in 7d8e5ae401d3ebb39dd83c513e105d256537b7c2 e16a1fe506274bd10fabd0d0dbc60f9fabc5d8d8
