### ISSUE TITLE
有没有什么方法,可以自动撤回指定图片?

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#26]
群友有时候莫名用一些很不舒服的图片刷屏,想给自动撤回

**Comment by Ailitonia** [comment]
这个不该问我，该去看go-cq文档 [撤回消息](https://docs.go-cqhttp.org/api/#%E6%92%A4%E5%9B%9E%E6%B6%88%E6%81%AF)

**Comment by lancer-wang** [comment]
找到了,这里是图片特征码,判断这个特征码就行
![image](https://user-images.githubusercontent.com/69783837/119591858-f6d3f080-be09-11eb-9efd-506c2ffeee62.png)
一会把数据加到数据库里
![image](https://user-images.githubusercontent.com/69783837/119591913-0ce1b100-be0a-11eb-95d0-35a10a5a3cc8.png)

**Comment by Ailitonia** [comment]
那个是图片id
实际上用message的type属性就可以判断了
https://github.com/Ailitonia/omega-miya/blob/3af524fbc8371dbf8fdede22f06614557de07560/omega_miya/plugins/Omega_anti_flash/__init__.py#L126-L127

**Comment by lancer-wang** [comment]
> 那个是图片id
> 实际上用message的type属性就可以判断了
> https://github.com/Ailitonia/omega-miya/blob/3af524fbc8371dbf8fdede22f06614557de07560/omega_miya/plugins/Omega_anti_flash/__init__.py#L126-L127

实际上我就是放到防闪照下面了.....
![image](https://user-images.githubusercontent.com/69783837/119752800-306f2f00-bed0-11eb-8de6-4d838c3ac0a2.png)
