### ISSUE TITLE
图片添加噪点防河蟹

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#27]
刚才看群友聊天说为了防和谐,有人用发作业的形式发涩图
然后忽然想起之防和谐做的发送前添加噪点,用了几个星期,效果还行,r18的都不会和谐掉

import  cv2
import numpy as np
def random_noise(image):
    '''
    添加随机噪点（实际上就是随机在图像上将像素点的灰度值变为255即白色）
    :param image: 需要加噪的图片途径
    :param noise_num: 添加的噪音点数目，几个就行
    :return: img_noise
    '''
    #
    noise_num = random.randint(1, 10)
    # 参数image：，noise_num：
    img = cv2.imread(image)
    img_noise = img
    # cv2.imshow("src", img)
    rows, cols, chn = img_noise.shape
    # 加噪声
    for i in range(noise_num):
        x = np.random.randint(0, rows)  # 随机生成指定范围的整数
        y = np.random.randint(0, cols)
        img_noise[x, y, :] = 255
    cv2.imwrite(image, img_noise)

**Comment by Ailitonia** [comment]
也算是个办法，我之前也写过类似的，只不过是使用高斯模糊处理图片
之后如果实现的话考虑用使用插件配置来启用

**Comment by lancer-wang** [comment]
主要这种比较简单比较快,然后和人交流,他们说腾讯是用md5检测的,这种方法目前是完全ok的

**Comment by lancer-wang** [comment]
你敢不敢再糊点?(笑哭)
![image](https://user-images.githubusercontent.com/69783837/120801141-60bf6900-c573-11eb-83dd-31ee5df2f234.png)
