### ISSUE TITLE
Future: Pixiv订阅

### ISSUE THREAD

**Issue by Ailitonia** [Ailitonia/omega-miya#28]
订阅画师作品更新
因画师作品内容不定，将不与萌图插件共用pixiv_illust表

**Comment by Ailitonia** [comment]
已完成

**Comment by lancer-wang** [comment]
感觉应该加个命令,能调画师作品的数据库的图片
比如来几张XX画师的作品

**Comment by Ailitonia** [comment]
> 感觉应该加个命令,能调画师作品的数据库的图片
> 比如来几张XX画师的作品

emmmm感觉和萌图插件的功能有点重复，我想想要怎么加这个功能（

**Comment by lancer-wang** [comment]
你可以用这种正则的方式搞,我自己加的功能都是用正则控制的
![image](https://user-images.githubusercontent.com/69783837/120893156-4f925d00-c644-11eb-94bd-c50fdaa56a7e.png)
