### ISSUE TITLE
pixiv根据pid获取作品多图问题

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#29]
这个功能好像是不可用的,我昨天试了发多图的pid,返回的只有第一张
我之前以为是没有这个功能,然后发现是好像功能失效了
![image](https://user-images.githubusercontent.com/69783837/120172423-9bed2f80-c235-11eb-967b-f48cf7158b3d.png)

**Comment by Ailitonia** [comment]
配置了P站的cookies吗？
https://github.com/Ailitonia/omega-miya/blob/937def089482da2e125f021bb848b1878369601d/.env.dev#L47-L49
不配置的话P站api拿不到信息
建议浏览器直接访问 https://www.pixiv.net/ajax/illust/{pid}/pages
没有登陆或P站设置没开的返回是
```JavaScript
{error: true, message: "该作品已被删除，或作品ID不存在。", body: []}
```
而且状态码是404

**Comment by lancer-wang** [comment]
配倒是配了,是不是没加引号?
![image](https://user-images.githubusercontent.com/69783837/120252880-66d5f100-c2b8-11eb-803c-abbe26638a45.png)

**Comment by Ailitonia** [comment]
不需要加引号呀

在这里后面加一个print

https://github.com/Ailitonia/omega-miya/blob/937def089482da2e125f021bb848b1878369601d/omega_miya/utils/pixiv_utils/pixiv.py#L159-L161

```python
print(illust_pages_result)
```

然后提供一下完整日志看看呢

**Comment by Ailitonia** [comment]
对了，上面提到的P站设置是配置cookies对应账号的设置里面这个选项要开
![image](https://user-images.githubusercontent.com/41713304/120255847-76a50380-c2bf-11eb-8d34-6879156ffef2.png)

**Comment by lancer-wang** [comment]
我看了下,你的用pid搜索的时候,确实只会给第一张,不过后面有个pixivdl方法,打包上传会获取所有图片
![image](https://user-images.githubusercontent.com/69783837/120255747-452c3800-c2bf-11eb-9f5d-21066333f633.png)

**Comment by Ailitonia** [comment]
是这样的啊，/pixiv 的确只发第一张图的
只有/pixivdl 才可以发送全部图片

**Comment by lancer-wang** [comment]
> 是这样的啊，/pixiv 的确只发第一张图的
> 只有/pixivdl 才可以发送全部图片
> 所以你之前说的是这个问题吗😂

我是今天才发现有个pixivdl,我一直以为是搜pid可以看所有
那我本地给魔改一下吧,我还是想看全部的

**Comment by Ailitonia** [comment]
> 我是今天才发现有个pixivdl,我一直以为是搜pid可以看所有
> 那我本地给魔改一下吧,我还是想看全部的

这里可以自己魔改了，毕竟我考虑的是要是遇到图片很多的插画一次性下载和发送的时候，bot 机器的小水管扛不住😂

**Comment by lancer-wang** [comment]
魔改了,感觉速度区别不大,可能是我放到外服的原因吧,不过这里如果用cat的代理的话,国内应该速度也可以
