### ISSUE TITLE
Future: 支持Pixiv动图下载后生成GIF

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#31]
原因不明

**Comment by Ailitonia** [comment]
因为pixiv的动图不是gif😂

P站的动图是单独加载每一帧然后播放

你F12看看就明白了

~~经常从P站扒图的人都知道（~~

**Comment by Ailitonia** [comment]
可以通过 https://www.pixiv.net/ajax/illust/{pid}/ugoira_meta 来获取动图单帧信息，包括每帧的持续时间

你可以参考 [FoXZilla/Pxer](https://github.com/FoXZilla/Pxer) 中的 [这部分](https://github.com/FoXZilla/Pxer/blob/774c15f963f1d1d921ecf7f7095c42911ec550e3/src/app/PxerPrinter.js#L194-L216) 内容编写一个自动生成GIF的脚本（需要用到ffmpeg）

~~其实一开始我就想借鉴一下的但是考虑到机器性能问题以及ffmpeg处理的时间最后就放弃了~~

**Comment by lancer-wang** [comment]
应该是这两年改了格式吧,之前我记得直接就是动图的

**Comment by lancer-wang** [comment]
你还别说,我真找到了个简单的方法 ,https://github.com/OrsPced/PixivRankDownload
一张23m的动图大概耗时17s,感觉还行

![image](https://user-images.githubusercontent.com/69783837/120736601-1b714c00-c51f-11eb-94cd-7e4aa4d0cdbb.png)

**Comment by Ailitonia** [comment]
imageio.mimsave 直接写啊，学到了😂
~~这就去借鉴一个~~
