### ISSUE TITLE
我又想到一个功能

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#33]
不是经常有一些乱七八糟的邀人活动吗
![image](https://user-images.githubusercontent.com/69783837/121112574-2d1a6280-c843-11eb-84b2-8042b94083b5.png)
可以做个功能,根据指定的关键词,撤回发言
大致想了想,然后我直接加到防闪图下面了
![image](https://user-images.githubusercontent.com/69783837/121113998-9307e980-c845-11eb-9dda-1f3a425e21bb.png)

**Comment by Ailitonia** [comment]
这个从广义上来说算是群管插件的功能了😂
相关功能大概会在后面慢慢添加
这里就先放个 #TODO 吧
