### ISSUE TITLE
连接时提示bad handshake

### ISSUE THREAD

**Issue by YokiiroBW** [Ailitonia/omega-miya#34]
部署完毕后一直提示这个，换了好多端口都不行，想请问一下是怎么回事。
![image](https://user-images.githubusercontent.com/82425598/121140688-b8f4b480-c86c-11eb-8182-f3434f00ddd4.png)

**Comment by lancer-wang** [comment]
最好贴一下go-cqhttp和 本地env文件的配置
这样只能判断你是二者之一配置有问题

**Comment by Ailitonia** [comment]
请提供完整的nonebot2 env配置文件及go-cqhttp培训文件
不然无法判断是哪里的问题

**Comment by YokiiroBW** [comment]
![image](https://user-images.githubusercontent.com/82425598/121151462-f78f6c80-c876-11eb-9458-ddfa4b7eb457.png)
![image](https://user-images.githubusercontent.com/82425598/121151563-0fff8700-c877-11eb-8605-d2897083405e.png)
这是配置文件

**Comment by Ailitonia** [comment]
检查你两端的ACCESS_TOKEN是不是一样的
或者不要配置ACCESS_TOKEN
第二张截图没截全不过我觉得大概率是这个问题

**Comment by YokiiroBW** [comment]
解决了，确实是没有配置ACCESS_TOKEN的原因，非常感谢。
