### ISSUE TITLE
专辑订阅这种我感觉还是放到合并转发比较好吧

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#36]
主要图片比较多,容易刷屏,没在聊天的时候还好,如果是在聊天,就很影响
而且专辑内容比较和谐,应该不太会被风控

**Comment by Ailitonia** [comment]
可以，再加个选项就好了
之前没用过自定义转发节点，我先看看怎么搞

**Comment by lancer-wang** [comment]
发现一个很奇怪的东西,如果机器人被禁言,订阅会发不出去,然后貌似还有其他奇怪的问题

**Comment by lancer-wang** [comment]
专辑发送报错
![image](https://user-images.githubusercontent.com/69783837/121801259-07d58c00-cc69-11eb-8db3-513789a1d667.png)

**Comment by Ailitonia** [comment]
> 专辑发送报错

好像是MsgSender里面不小心使用了<>符号导致转义错误😂是我手滑了

**Comment by Ailitonia** [comment]
已修改
