### ISSUE TITLE
readme中python要求是3.8+，部分插件实际可能需要更高版本

### ISSUE THREAD

**Issue by ShianoQwQ** [Ailitonia/omega-miya#48]
readme里python要求是3.8+，已安装的python版本是3.8.10，使用抽卡时报错
`TypeError: sample() got an unexpected keyword argument 'counts'`
发现使用的random.sample()的参数counts不支持，查询python文档后发现在3.9才添加的counts参数[random.sample](https://docs.python.org/zh-cn/3/library/random.html#random.sample)，更换到python3.9.5后可以正常使用了。

**Comment by Ailitonia** [comment]
是我疏忽了，下次合并的时候会把 README 里面的版本要求更新的
