### ISSUE TITLE
git对文件名大小写不敏感，仓库dev分支未更新包名导致导入错误

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#51]

**Comment by lancer-wang** [comment]
![image](https://user-images.githubusercontent.com/69783837/129499295-193b89b2-12e2-490a-848d-4f6e16fc8d67.png)
是不是多删还是少删东西了

**Comment by lancer-wang** [comment]
找到问题了omega_plugin_utils应该是Omega_plugin_utils

**Comment by lancer-wang** [comment]
win不区分大小写,linux区分

**Comment by Ailitonia** [comment]
看了下，我本地修改了包名后git未识别为更新一并提交，可能是系统没有区分大小写

**Comment by Ailitonia** [comment]
稍后我挨个处理下吧

**Comment by Ailitonia** [comment]
Fixed in c896423abe57cb57a74b6f109fdb66a96ab54876
