### ISSUE TITLE
签到触发两次

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#53]
是否与我设置的配置文件,可以不加分号触发命令有关
![image](https://user-images.githubusercontent.com/69783837/132430584-5043f94c-3e75-4050-8db6-a300d18328f4.png)

**Comment by lancer-wang** [comment]
似乎是因为同时触发了这两个
![image](https://user-images.githubusercontent.com/69783837/132430967-3841078b-8c59-40e3-9b65-817f00b74228.png)

**Comment by Ailitonia** [comment]
我觉得可能和命令前缀有关
我设置了命令前缀所以单独加了个on_regex来匹配消息
你可能命令前缀为空所以同时触发了这两个

稍后我去加个配置选项吧

**Comment by Ailitonia** [comment]
Fixed in 993ce7cc99feb5625ab6f5e195a37618f1f427de
