### ISSUE TITLE
没有群组命令权限

### ISSUE THREAD

**Issue by sola614** [Ailitonia/omega-miya#55]
没配置超级用户的qq号无法使用命令吗？另外问一下机器人是在国内服务器挂的，http代理应该怎么搞？难道装个v2ray吗？

**Comment by Ailitonia** [comment]
命令权限配置可以参考[本仓库wiki-启用功能和分配权限](https://github.com/Ailitonia/omega-miya/wiki/%E5%90%AF%E7%94%A8%E5%8A%9F%E8%83%BD%E5%92%8C%E5%88%86%E9%85%8D%E6%9D%83%E9%99%90)

或者参考管理插件说明

https://github.com/Ailitonia/omega-miya/blob/5ac8331ca77217ab6c3db7dd8a0ecc6072f2ab94/omega_miya/plugins/Omega_manager/__init__.py#L2-L8

至于 http 代理完全看你习惯用什么，本地安装代理软件或者代理服务器开放 http 代理端口都可以

**Comment by sola614** [comment]
原来是我看文档没看全，http那个我再看看怎么弄，谢谢
