### ISSUE TITLE
功能建议:早上/中午/晚上/夜宵吃啥

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#63]
灵感来自于https://github.com/pcrbot/whattoeat
我感觉他做的不够详细,可以把食物细分为早上,中午,晚上,夜宵等
发对应的命令,出对应类型的图片

**Comment by Ailitonia** [comment]
Add in 67be102d6344d5dda0d61de05ea96154b9f61cbf

更多图片素材待补充……

**Comment by ShianoQwQ** [comment]
我正好也想写个这个功能，一开始想的是丢到求签的卡组里
不过现在看如果有图感觉更好
*准备去爬点免费图*

**Comment by Ailitonia** [comment]
增加了更多的菜品 6c7bcc17d8ea45c973404a62992bff6bd18c40e4
