### ISSUE TITLE
报错提问

### ISSUE THREAD

**Issue by BalconyJH** [Ailitonia/omega-miya#64]
签到/运势等功能无法使用
![image](https://user-images.githubusercontent.com/73932916/140644379-0502634e-b80b-4480-bf0e-689dbd92f2a5.png)

**Comment by BalconyJH** [comment]
每一轮timeout过后都会重复提交尝试，产生大量log文件
![image](https://user-images.githubusercontent.com/73932916/140648682-3c49ed9e-95cd-4b4a-832a-ff899750d927.png)

**Comment by BalconyJH** [comment]
最后提示这个
![image](https://user-images.githubusercontent.com/73932916/140648729-5f600b9e-e53d-4636-be11-820957670782.png)

**Comment by Ailitonia** [comment]
签到图片来源是 pixiv，无法访问 pixiv 的话是获取不到图片资源的
请尝试使用代理或将服务端部署在能访问 pixiv 的网络环境

**Comment by BalconyJH** [comment]
请教一下代理如何配置
![image](https://user-images.githubusercontent.com/73932916/140693377-b95eaf29-9fec-4c95-b154-00064a113398.png)
gocq是否需要填入相应字段
![image](https://user-images.githubusercontent.com/73932916/140693439-6c8170b7-e615-403c-9c73-3c4ff12018d5.png)

**Comment by Ailitonia** [comment]
代理配置把 ENABLE_PROXY 设置为 true

配置地址端口照填

gocq不需要代理

**Comment by BalconyJH** [comment]
需要开放服务器相应端口放行吗

**Comment by BalconyJH** [comment]
![image](https://user-images.githubusercontent.com/73932916/140749901-17806e52-3ba3-4a46-abf3-86b58017d2a0.png)
![image](https://user-images.githubusercontent.com/73932916/140749947-0c3984fe-de06-4c4c-98a5-43a984f87060.png)
![image](https://user-images.githubusercontent.com/73932916/140749989-01b09801-16e4-48c4-bd82-585711d32ff0.png)
ip能ping通但无法成功代理，服务器相应端口已开放

**Comment by Ailitonia** [comment]
ping ip 能通不代表端口开放

![image](https://user-images.githubusercontent.com/41713304/140750978-ac086d35-af55-4f5e-a72d-f0902f2ccf07.png)

请使用 **可用的** **HTTP** 代理

**Comment by BalconyJH** [comment]
感谢
