### ISSUE TITLE
订阅warning

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#68]
![image](https://user-images.githubusercontent.com/69783837/145926817-99cf5215-b31e-49b4-8d3b-beb0a8792ee7.png)
/usr/local/lib/python3.9/dist-packages/apscheduler/triggers/cron/__init__.py:159: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.localize(datetime(**values))
/usr/local/lib/python3.9/dist-packages/apscheduler/triggers/cron/__init__.py:146: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(dateval + difference), fieldnum

![image](https://user-images.githubusercontent.com/69783837/145926828-3d433bd7-b5b0-4852-840f-0246215ab343.png)

/usr/local/lib/python3.9/dist-packages/apscheduler/util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':

**Comment by lancer-wang** [comment]
![image](https://user-images.githubusercontent.com/69783837/145926915-c8a9bf03-d915-464e-867b-5b2edf244324.png)
时区也是对的啊

**Comment by Ailitonia** [comment]
上游问题，功能没问题的话可以忽略

参见https://github.com/nonebot/nonebot2/issues/595#issuecomment-973775890
