### ISSUE TITLE
这个报错咋弄

### ISSUE THREAD

**Issue by CMMG6688** [Ailitonia/omega-miya#69]
![IMG_20211215_154623](https://user-images.githubusercontent.com/57741734/146144705-9072ee39-f30c-4707-8e2a-f4b038058d5b.jpg)

**Comment by Ailitonia** [comment]
请检查一下配置文件中 MySQL 配置部分的密码 DB_PASSWORD 项

这个报错是类型错误，请确认你配置的是个字符串

**Comment by CMMG6688** [comment]
ok，解决了，一开始我密码填的数字，现在改过来了。
