### ISSUE TITLE
订阅出错不知道为什么

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#70]
![image](https://user-images.githubusercontent.com/69783837/147450378-6d6dc77a-4740-4299-8e6c-ab621148cf01.png)

**Comment by Ailitonia** [comment]
这看起来像是网络问题啊
全是 timeout

**Comment by Ailitonia** [comment]
而且全是在下载图片的时候超时的

**Comment by lancer-wang** [comment]
好像是我服务器的问题,下载图片就卡,其他正常,很诡异

**Comment by lancer-wang** [comment]
换了个服务器,正常了
