### ISSUE TITLE
签到插件启动出错

### ISSUE THREAD

**Issue by G41mywaifu** [Ailitonia/omega-miya#72]
启动时会报错def __get_level(favorability: float) -> tuple[int, int, int]: 的 'type' object is not subscriptable
 但我删掉-> tuple[int, int, int]就能正常使用   能知道是什么原因吗

**Comment by Ailitonia** [comment]
类型标注泛型，请更新 python 到 3.9 以上版本

参见[Python 3.9 更新文档](https://docs.python.org/zh-cn/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections)

**Comment by G41mywaifu** [comment]
好的 谢谢
