### ISSUE TITLE
support for nonebot2-2.0.0-beta2

### ISSUE THREAD

**Issue by Heartfirey** [Ailitonia/omega-miya#81]
support for nonebot2-2.0.0-beta2

**Comment by Ailitonia** [comment]
适配正在~~摸鱼~~进行中，因为趁着适配 beta2 进行了整体的重构，所以用时比较长。
新版本数据库结构与当前版本相比有较大变化，发布后当前版本将冻结，并提供基础的数据库迁移工具。

~~现在刚刚把数据库和工具类写完，插件的重构还没开始~~
