### ISSUE TITLE
Question：Omega miya 如何和go-cqhttp配合使用

### ISSUE THREAD

**Issue by LXPWing** [Ailitonia/omega-miya#82]
请教下 Omega miya 中的.env.prod文件中如何配置go-cqhttp

**Comment by Ailitonia** [comment]
配置 go-cqhttp 部分已在 .env.dev 中有示例
https://github.com/Ailitonia/omega-miya/blob/53a6683fccb0618e306abe9e103cec78445f3796/.env.dev#L1-L9

请自行参考[文档-协议适配-CQHTTP 协议使用指南-反向 WebSocket 连接](https://61d3d9dbcadf413fd3238e89--nonebot2.netlify.app/guide/cqhttp-guide.html#%E9%80%89%E9%A1%B9-1-%E5%8F%8D%E5%90%91-websocket-%E8%BF%9E%E6%8E%A5)以及[文档-API-NoneBot.config 模块](https://61d3d9dbcadf413fd3238e89--nonebot2.netlify.app/api/config.html)说明进行配置

**Comment by LXPWing** [comment]
thanks
