### ISSUE TITLE
关于nh下载搜索本子

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#89]
nh现在开了cloudflare反爬,用不了了
![image](https://user-images.githubusercontent.com/69783837/168785250-6efec187-55eb-49ac-8f26-5c4d56e654c5.png)

**Comment by Ailitonia** [comment]
用这个 header 试试?
`{'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0'}`

**Comment by Ailitonia** [comment]
好像没啥用😂
cf有点烦，我去研究研究有没有啥好用的处理方法

**Comment by lancer-wang** [comment]
我这里依然会被拦，算了先放着吧
