### ISSUE TITLE
连接不上无限报错

### ISSUE THREAD

**Issue by fuyuan140** [Ailitonia/omega-miya#90]
![-73552ff7a243bf9e](https://user-images.githubusercontent.com/90545638/169650064-b21ed166-b684-444c-8494-eae1c40b68bf.png)
#

**Comment by Ailitonia** [comment]
请检查 `.env` 中的 `ONEBOT_ACCESS_TOKEN` 配置与 go-cqhttp 的 `access-token` 是否一致

**Comment by fuyuan140** [comment]
问题依旧存在，配置文件如下![Uploading 5185bae78983e7e7.png…]()
![-437c8973e6386f7b](https://user-images.githubusercontent.com/90545638/169656594-efae5192-aef9-44af-870d-86040ff90481.png)
![682039311d6971d](https://user-images.githubusercontent.com/90545638/169656595-92684b47-5188-4531-ac3b-2c542e7f332d.png)
![-5a4916e9ae953656](https://user-images.githubusercontent.com/90545638/169656598-512c0b3c-8e1f-40c3-9875-96e375b70855.png)

**Comment by fuyuan140** [comment]
问题依旧存在，配置文件如下![5185bae78983e7e7](https://user-images.githubusercontent.com/90545638/169656619-64b3d11f-a422-4c37-a7f6-f464b99bf76c.png)
![-437c8973e6386f7b](https://user-images.githubusercontent.com/90545638/169656623-2f79bb8a-3c67-4e0a-953c-77e8d1564284.png)
![682039311d6971d](https://user-images.githubusercontent.com/90545638/169656629-0033cdb2-55d4-449a-b7f3-a3a8cf7584f9.png)
![-5a4916e9ae953656](https://user-images.githubusercontent.com/90545638/169656631-a2812400-e4ab-4cba-8a32-2935835116b6.png)

**Comment by fuyuan140** [comment]
解决了，感谢
