### ISSUE TITLE
dev版本无限报错

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#91]
![image](https://user-images.githubusercontent.com/69783837/171362031-bc441c53-c988-41ef-af42-5dcd46ae656f.png)

**Comment by lancer-wang** [comment]
requirements.txt安装了,旧版本全部删除,重新从github下的就是这样

**Comment by lancer-wang** [comment]
![image](https://user-images.githubusercontent.com/69783837/171368541-2d3e3d0a-18b4-424b-ada5-c7ac78609e94.png)
两种报错

**Comment by lancer-wang** [comment]
删掉之前pip安装的包,重新安装,也是不行

**Comment by lancer-wang** [comment]
我是ubuntu20,python3.9.9, x86_64架构

**Comment by lancer-wang** [comment]
![image](https://user-images.githubusercontent.com/69783837/171534857-078d8554-4488-4907-9ed6-c5cb1a545a93.png)
这个我也配置了,就是还是403
![image](https://user-images.githubusercontent.com/69783837/171534989-916ea2ef-6c00-40e8-9a8d-2887559772be.png)

**Comment by lancer-wang** [comment]
> dev 需要 python 3.10 第一个是 3.10 类型提示的[新特性](https://docs.python.org/zh-cn/3/whatsnew/3.10.html#new-features-related-to-type-hints) 第二个是 3.10 新加入的[结构化模式匹配](https://docs.python.org/zh-cn/3/whatsnew/3.10.html#pep-634-structural-pattern-matching)

改了3.10之后能启动了

**Comment by lancer-wang** [comment]
![image](https://user-images.githubusercontent.com/69783837/171542188-8feee986-c3e0-4bc4-875f-bd645ff6ed70.png)

**Comment by lancer-wang** [comment]
![image](https://user-images.githubusercontent.com/69783837/171546076-cb05c793-5279-472b-be15-9468678a378d.png)
![image](https://user-images.githubusercontent.com/69783837/171546111-a0d30011-a935-49ae-b50b-71ab58d78a35.png)
改用http模式也不行

**Comment by Ailitonia** [comment]
> ![image](https://user-images.githubusercontent.com/69783837/171542188-8feee986-c3e0-4bc4-875f-bd645ff6ed70.png)

你反向 ws 地址没对啊，应该是
`ws://127.0.0.1:port/onebot/v11/ws/`
新版 adapter 不是早就改了吗，看[文档](https://onebot.adapters.nonebot.dev/docs/guide/setup#%E5%8F%8D%E5%90%91-websocket-%E8%BF%9E%E6%8E%A5%E6%8E%A8%E8%8D%90)

**Comment by lancer-wang** [comment]
> > ![image](https://user-images.githubusercontent.com/69783837/171542188-8feee986-c3e0-4bc4-875f-bd645ff6ed70.png)
> 
> 你反向 ws 地址没对啊，应该是 `ws://127.0.0.1:port/onebot/v11/ws/` 新版 adapter 不是早就改了吗，看[文档](https://onebot.adapters.nonebot.dev/docs/guide/setup#%E5%8F%8D%E5%90%91-websocket-%E8%BF%9E%E6%8E%A5%E6%8E%A8%E8%8D%90)

终于可以了,刚才还自作聪明用v12....
![image](https://user-images.githubusercontent.com/69783837/171550330-ef85f950-cdb1-46b3-90e5-18ea0907cc2e.png)
