### ISSUE TITLE
用户订阅bug

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#93]
omega_miya/plugins/pixiv/__init__.py 第540行handle_check_add_user_id
这个方法里面应该加一下把user_id放到state,不然后面获取不到
![image](https://user-images.githubusercontent.com/69783837/171778891-97725d5b-35ca-44b5-81e2-1e863dbf25d6.png)

**Comment by Ailitonia** [comment]
这里没有问题啊
`matcher.got` 是会确保参数 `key` 存在于 `state` 中的, `handle_check_add_user_id` 这个处理依赖只是为了检验用户输入的 `user_id` 是不是存在的, 不需要再手动给 `state` 赋值

有问题的话可以贴错误日志

**Comment by lancer-wang** [comment]
我是这里报错,断点打印出来发现这里没有user_id,然后我就给他赋了个值
如果是pixiv用户订阅 user_id 是没有问题的
但是如果用pixiv用户订阅
然后输入user_id就会获取不到

**Comment by lancer-wang** [comment]
顺便问下,我上面那个关闭的issue的第一条,那个warning有影响吗

**Comment by Ailitonia** [comment]
这里确实有问题, 但不是没获取到 `user_id`, 而是 `got` 直接存到 `state` 里的是 `Message`, 导致
https://github.com/Ailitonia/omega-miya/blob/a5715f67893ce876e1321a8099567890f70e72ca/omega_miya/plugins/pixiv/__init__.py#L545
这里直接 `int(user_id)` 引发了 `TypeError` 异常
b站订阅插件也有类似的问题

需要写个依赖来修复这个问题

**Comment by lancer-wang** [comment]
> 这里确实有问题, 但不是没获取到 `user_id`, 而是 `got` 直接存到 `state` 里的是 `Message`, 导致
> 
> https://github.com/Ailitonia/omega-miya/blob/a5715f67893ce876e1321a8099567890f70e72ca/omega_miya/plugins/pixiv/__init__.py#L545
> 
> 
> 这里直接 `int(user_id)` 引发了 `TypeError` 异常
> b站订阅插件也有类似的问题
> 需要写个依赖来修复这个问题

我断点打印出来不是typeErrot,是直接没有值,所以才重新赋值的

**Comment by Ailitonia** [comment]
Fixed in 52b2033debd45dafb78aea0465517151bcb22e19
