### ISSUE TITLE
Database upgrade Failed

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#95]
Database upgrade Failed: ValidationError(model='ParsingModel[list[omega_miya.onebot_api.gocq.model.group.GroupInfo]]', errors=[{'loc': ('__root__', 0, 'group_memo'), 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ('__root__', 1, 'group_memo'), 'msg': 'field required', 'type': 'value_error.missing'}])

**Comment by Ailitonia** [comment]
go-cqhttp rc2 版本 `get_group_info` 和 `get_group_list` API 响应数据内容有变化, `group_memo` 字段似乎被移除了
目前 go-cqhttp 文档尚未更新, 不清楚是否有更多其他的变化

**Comment by Ailitonia** [comment]
Fixed in 8b1b7cb49e4bbd0901c66e3c74f349223c6e17c9
